INCLUDE memory_chip.x

REGION_ALIAS("REGION_TEXT", FLASH)
REGION_ALIAS("REGION_RODATA", FLASH)
REGION_ALIAS("REGION_DATA", RAM_HIGH)
REGION_ALIAS("REGION_BSS", RAM_HIGH)
REGION_ALIAS("REGION_STACK", RAM_HIGH)
REGION_ALIAS("REGION_HEAP", RAM_HIGH)
